var provincias = [
                    {'region' : 'Ninguna', 'name' : 'Ciudad Aut&oacute;noma de Buenos Aires', 'capital' : 'C.A.B.A', 'inhabitants' : '2.890.151', 'area' : '200' },
                    {'region' : 'Ninguna', 'name' : 'Buenos Aires', 'capital' : 'La Plata', 'inhabitants' : '15.625.084', 'area' : '307.571' },
                    {'region' : 'Norte Grande Argentino', 'name' : 'Catamarca', 'capital' : 'San Fernando del Valle de Catamarca', 'inhabitants' : '367.828', 'area' : '99.633' },
                    {'region' : 'Norte Grande Argentino', 'name' : 'Chaco', 'capital' : 'Resistencia', 'inhabitants' : '1.055.259', 'area' : '102.602' },
                    {'region' : 'Patag&oacute;nica', 'name' : 'Chubut', 'capital' : 'Rawson', 'inhabitants' : '509.108', 'area' : '224.686' },
                    {'region' : 'Centro', 'name' : 'C&oacute;rdoba', 'capital' : 'C&oacute;rdoba', 'inhabitants' : '3.308.876', 'area' : '165.321' },
                    {'region' : 'Norte Grande Argentino', 'name' : 'Corrientes', 'capital' : 'Corrientes', 'inhabitants' : '992.595', 'area' : '88.199' },
                    {'region' : 'Centro', 'name' : 'Entre R&iacute;os', 'capital' : 'Paran&aacute;', 'inhabitants' : '1.235.994', 'area' : '78.781' },
                    {'region' : 'Norte Grande Argentino', 'name' : 'Formosa', 'capital' : 'Formosa', 'inhabitants' : '530.162', 'area' : '72.066' },
                    {'region' : 'Norte Grande Argentino', 'name' : 'Jujuy', 'capital' : 'San Salvador de Jujuy', 'inhabitants' : '673.307', 'area' : '53.219' },
                    {'region' : 'Patag&oacute;nica', 'name' : 'La Pampa', 'capital' : 'Santa Rosa', 'inhabitants' : '318.951', 'area' : '143.440' },
                    {'region' : 'Nuevo Cuyo', 'name' : 'La Rioja', 'capital' : 'Rioja', 'inhabitants' : '333.642', 'area' : '89.680' },
                    {'region' : 'Nuevo Cuyo', 'name' : 'Mendoza', 'capital' : 'Mendoza', 'inhabitants' : '1.738.929', 'area' : '148.827' },
                    {'region' : 'Norte Grande Argentino', 'name' : 'Misiones', 'capital' : 'Posadas', 'inhabitants' : '1.101.593', 'area' : '29.801' },
                    {'region' : 'Patag&oacute;nica', 'name' : 'Neuqu&eacute;n', 'capital' : 'Neuqu&eacute;n', 'inhabitants' : '551.266', 'area' : '94.078' },
                    {'region' : 'Patag&oacute;nica', 'name' : 'R&iacute;o Negro', 'capital' : 'Viedma', 'inhabitants' : '638.645', 'area' : '203.013' },
                    {'region' : 'Norte Grande Argentino', 'name' : 'Salta', 'capital' : 'Salta', 'inhabitants' : '1.214.441', 'area' : '155.488' },
                    {'region' : 'Nuevo Cuyo', 'name' : 'San Juan', 'capital' : 'San Juan', 'inhabitants' : '681.055', 'area' : '89.651' },
                    {'region' : 'Nuevo Cuyo', 'name' : 'San Luis', 'capital' : 'San Luis', 'inhabitants' : '432.310', 'area' : '76.748' },
                    {'region' : 'Patag&oacute;nica', 'name' : 'Santa Cruz', 'capital' : 'R&iacute;o Gallegos', 'inhabitants' : '273.964', 'area' : '243.943' },
                    {'region' : 'Centro', 'name' : 'Santa Fe', 'capital' : 'Santa Fe', 'inhabitants' : '3.194.537', 'area' : '133.007' },
                    {'region' : 'Norte Grande Argentino', 'name' : 'Santiago del Estero', 'capital' : 'Santiago del Estero', 'inhabitants' : '874.006', 'area' : '136.351' },
                    {'region' : 'Patag&oacute;nica', 'name' : 'Tierra del Fuego, Ant&aacute;rtida e Islas del Atl&aacute;ntico Sur', 'capital' : 'Ushuaia', 'inhabitants' : '127.205', 'area' : '21.5714' },
                    {'region' : 'Norte Grande Argentino', 'name' : 'Tucum&aacute;n', 'capital' : 'San Miguel de Tucum&aacute;n', 'inhabitants' : '1.448.188', 'area' : '22.524' },
               ];
